# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 15:24
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hash', models.TextField(unique=True)),
                ('file_name', models.TextField()),
                ('file_type', models.TextField()),
                ('mime', models.TextField()),
                ('credit_title', models.TextField()),
                ('credit_url', models.URLField()),
                ('source_method', models.CharField(choices=[('UPLD', 'Upload')], default='UPLD', max_length=4)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('rights_expiry', models.DateTimeField(default=None, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
