# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0002_auto_20160509_1550'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='MultimediaImage',
        ),
        migrations.AlterModelTable(
            name='multimedia',
            table='multimedia',
        ),
        migrations.AlterModelTable(
            name='multimediaimage',
            table='multimedia_image',
        ),
    ]
