# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0003_auto_20160509_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimedia',
            name='file',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
