# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-09 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0004_multimedia_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multimedia',
            name='rights_expiry',
        ),
    ]
