# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 16:23
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0005_remove_multimedia_rights_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multimedia',
            name='file',
        ),
        migrations.AddField(
            model_name='multimedia',
            name='resource_name',
            field=models.UUIDField(default=str(uuid.uuid4())),
            preserve_default=False,
        ),
    ]
