# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0008_auto_20160711_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimediaimage',
            name='height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multimediaimage',
            name='width',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
