# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 11:24
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0013_auto_20161227_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimedia',
            name='credit_title',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='credit_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
