# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import lowdown.core.verticals.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField()),
                ('vertical', lowdown.core.verticals.fields.VerticalField(choices=[('theprate', 'The Prate'), ('thedrab', 'The Drab')], max_length=32)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'author',
            },
        ),
    ]
