# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
