# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_auto_20170729_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(default='example', unique=True),
            preserve_default=False,
        ),
    ]
