# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='series',
            table='series',
        ),
    ]
