# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('slug', models.SlugField()),
                ('deleted', models.BooleanField(default=False)),
                ('section', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sections.Section')),
            ],
        ),
    ]
