# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-23 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_auto_20160509_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sections.Section'),
            preserve_default=False,
        ),
    ]
