# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0007_auto_20170720_1340'),
        ('topics', '0004_auto_20160727_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set([('section', 'slug')]),
        ),
        migrations.AlterModelTable(
            name='topic',
            table=None,
        ),
    ]
