# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interactive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_count', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InteractiveRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('revision_number', models.PositiveIntegerField(default=0)),
                ('public', models.BooleanField(default=False)),
                ('interactive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactives.Interactive')),
            ],
        ),
    ]
