# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactive',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
