# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactives', '0002_auto_20170727_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactiverelease',
            name='interactive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='interactives.Interactive'),
        ),
    ]
