# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-27 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0006_auto_20161227_2247'),
        ('content', '0015_auto_20161227_2247'),
        ('multimedia', '0013_auto_20161227_2247'),
        ('verticals', '0002_vertical_identifier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vertical',
        ),
    ]
