# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_auto_20160508_2030'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='section',
            table='section',
        ),
    ]
