# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-18 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verticals', '0001_initial'),
        ('sections', '0004_auto_20160727_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='vertical',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='verticals.Vertical'),
            preserve_default=False,
        ),
    ]
