# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0006_auto_20161227_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set([('vertical', 'slug')]),
        ),
        migrations.AlterModelTable(
            name='section',
            table=None,
        ),
    ]
