# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_contentrevision_authors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentrevision',
            old_name='specturm_document',
            new_name='spectrum_document',
        ),
    ]
