# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20160509_1524'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='content',
            table='content',
        ),
        migrations.AlterModelTable(
            name='contentdiscussion',
            table='content_discussion',
        ),
        migrations.AlterModelTable(
            name='contenteditorialmetadata',
            table='content_editorial_metadata',
        ),
        migrations.AlterModelTable(
            name='contentrevision',
            table='content_revision',
        ),
    ]
