# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-09 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20160509_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentdiscussion',
            name='author',
        ),
        migrations.RemoveField(
            model_name='contentdiscussion',
            name='content',
        ),
        migrations.RemoveField(
            model_name='contentdiscussion',
            name='content_revision',
        ),
        migrations.RemoveField(
            model_name='contenteditorialmetadata',
            name='assigned_user',
        ),
        migrations.RemoveField(
            model_name='contenteditorialmetadata',
            name='due_at',
        ),
        migrations.RemoveField(
            model_name='contenteditorialmetadata',
            name='embargoed_till',
        ),
        migrations.RemoveField(
            model_name='contenteditorialmetadata',
            name='watchers',
        ),
        migrations.DeleteModel(
            name='ContentDiscussion',
        ),
    ]
