# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20160709_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentrevision',
            name='slug',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
