# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0009_auto_20160711_2140'),
        ('content', '0006_auto_20160714_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentrevision',
            name='poster_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multimedia.Multimedia'),
        ),
    ]
