# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_contentrevision_poster_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='published_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
