# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_content_published_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentrevision',
            name='standfirst',
            field=models.TextField(blank=True),
        ),
    ]
