# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-24 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_auto_20160509_1559'),
        ('content', '0009_contentrevision_standfirst'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentrevision',
            name='section',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_revisions', to='sections.Section'),
        ),
    ]
