# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_contentrevision_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenteditorialmetadata',
            name='status',
        ),
        migrations.AddField(
            model_name='contentrevision',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Stub'), (5, 'Draft'), (7, 'Review'), (9, 'Final')], default=1),
        ),
    ]
