# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-26 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20160725_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='published_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='published_updated_date',
            field=models.DateTimeField(null=True),
        ),
    ]
