# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20161227_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='published_slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentrevision',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Stub'), (5, 'Draft'), (7, 'Review'), (9, 'Final')], default=5),
        ),
    ]
