# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_auto_20170719_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentrevision',
            old_name='authors',
            new_name='users',
        ),
    ]
