# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('content', '0017_auto_20170719_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentrevision',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='content_revisions', to='authors.Author'),
        ),
    ]
