# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_contentrevision_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='published_slug',
            field=models.SlugField(blank=True, max_length=60, null=True),
        ),
    ]
