# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_auto_20170726_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentrevision',
            name='tone',
            field=models.SmallIntegerField(choices=[(1, 'Content'), (2, 'Review'), (3, 'Viewpoint'), (4, 'Storytelling'), (5, 'Interactive'), (6, 'Guide'), (7, 'News')], db_index=True),
        ),
    ]
