# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_auto_20170729_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentrevision',
            name='preview_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
