# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 16:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0021_contentrevision_preview_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentrevision',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to=settings.AUTH_USER_MODEL),
        ),
    ]
