# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_auto_20170924_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenteditorialmetadata',
            name='relevant_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
