# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_contenteditorialmetadata_relevant_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenteditorialmetadata',
            options={'permissions': (('finalize_content', 'Can finalize'), ('publish', 'Can publish'), ('save_watching', 'Can save watching'), ('save_any', 'Can save any'))},
        ),
    ]
